name: framy_annotation
description: >
  Annotations for framy_generator.
  This package does nothing without framy_generator.
version: 0.1.1
repository: https://github.com/Fidev-io/framy
homepage: https://framy.dev

environment:
  sdk: ">=2.5.0 <3.0.0"

